// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CHASSIS_H
#define CHASSIS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Chassis: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* leftDrive;
	SpeedController* rightDrive;
	SpeedController* sideDrive;
	Encoder* rightEn;
	Encoder* leftEn;
	Encoder* sideEn;
	Gyro* gyro;
	BuiltInAccelerometer* acc;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Chassis();
	void InitDefaultCommand();
	void Move(Joystick *leftJoy, Joystick *rightJoy);
	void ToggleStrafe();

	float yPosLeft;
	float yStepLeft;

	float yPosRight;
	float yStepRight;

	float xPos;
	float xStep;

	float accelval;

	float stoppedRight;
	float stoppedLeft;
	float stoppedSide;

	bool strafe;
	Timer t; //Creates new timer t

	DoubleSolenoid* strafeSol;

	float ax;
	float vx;
	float px;
	float ay;
	float vy;
	float py;
};

#endif
