// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Chassis.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/Drive.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Timer t;

Chassis::Chassis() : Subsystem("Chassis") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftDrive = RobotMap::chassisleftDrive;
	rightDrive = RobotMap::chassisrightDrive;
	sideDrive = RobotMap::chassissideDrive;
	rightEn = RobotMap::chassisrightEn;
	leftEn = RobotMap::chassisleftEn;
	sideEn = RobotMap::chassissideEn;
	gyro = RobotMap::chassisgyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

    
void Chassis::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Chassis::Move(Joystick* leftJoy, Joystick* rightJoy) {

	float yPosLeft = 0;
	float yStepLeft = yPosLeft;

	float yPosRight = 0;
	float yStepRight = yPosRight;

	float xPos = 0;
	float xStep = xPos;

	float accelval = 15;

	float stoppedRight = 0;
	float stoppedLeft = 0;
	float stoppedSide = 0;

	t.Start();
	t.Reset();

	yPosLeft = (leftJoy->GetY() + (accelval * yStepLeft))/(accelval + 1);
	yStepLeft = yPosLeft;
	if(abs((leftJoy->GetY())-yPosLeft)<.5 && (t.Get() - stoppedLeft) > .25)  {
		yStepLeft = leftJoy->GetY();
		stoppedLeft = t.Get();
	}

	yPosRight = (rightJoy->GetY() + (accelval * yStepRight))/(accelval + 1);
	yStepRight = yPosRight;
	if(abs((rightJoy->GetY())-yPosRight)<.5 && (t.Get() - stoppedRight) > .25)  {
		yStepRight = rightJoy->GetY();
		stoppedRight = t.Get();
	}

	xPos = (leftJoy->GetX() + (accelval * xStep))/(accelval + 1);
	xStep = xPos;
	if(abs((leftJoy->GetX())-xPos)<.5 && (t.Get() - stoppedSide) > .25)  {
		xStep = leftJoy->GetX();
		stoppedSide = t.Get();
	}

	Robot::chassis->leftDrive->Set(yPosLeft);
	Robot::chassis->rightDrive->Set(yPosRight);
	Robot::chassis->sideDrive->Set(xPos);
}


