// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"



AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	counter = 0;
	centerdistance=0;
	startonleft=false;
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	centerdistance=0;
	startonleft=false;
	counter=0;
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	centerdistance=	Robot::table->GetNumber("Midpoint",0);
}

void AutonomousCommand::GoForward() {
	Robot::chassis->leftDrive->Set(1);
	Robot::chassis->rightDrive->Set(-1);

	//activate pick up mechanism/function
	//pickup activates GoBackward() once done
}

void AutonomousCommand::GoBackward() {
	Robot::chassis->leftDrive->Set(-1);
	Robot::chassis->rightDrive->Set(1);
	counter++;
	if(startonleft==true) {
		Robot::chassis->sideEn->Reset();
		StrafeRight(500);
	}else{
		Robot::chassis->sideEn->Reset();
		StrafeLeft(500);
	}
}

void AutonomousCommand::StrafeLeft(int strafeamount) {
	Robot::chassis->sideDrive->Set(1);
	if(Robot::chassis->sideEn->Get()>strafeamount||Robot::chassis->sideEn->Get()<-1*strafeamount) {
		Robot::chassis->sideDrive->Set(0);
		Angle();
	}
}



void AutonomousCommand::StrafeRight(int strafeamount) {
	Robot::chassis->sideDrive->Set(-1);
	if(Robot::chassis->sideEn->Get()>strafeamount||Robot::chassis->sideEn->Get()<-1*strafeamount) {
		Robot::chassis->sideDrive->Set(0);
		Angle();
	}
}


void AutonomousCommand::Angle() {
	if(Robot::table->GetNumber("Angle",0)>1.01) {
		Robot::chassis->rightDrive->Set(1);
		Robot::chassis->leftDrive->Set(-1);
		Angle();
		StrafeLeft(20);
	}
	if(Robot::table->GetNumber("Angle",0)<.99) {
		Robot::chassis->rightDrive->Set(-1);
		Robot::chassis->leftDrive->Set(1);
		Angle();
		StrafeRight(20);
	}
	if(Robot::table->GetNumber("Angle",0)>.99&&Robot::table->GetNumber("Angle",0)<1.01) {
		Center();
	}
}

void AutonomousCommand::Center() {
	if(centerdistance<-5) {
		Robot::chassis->sideDrive->Set(1);
	}
	if(centerdistance>5) {
		Robot::chassis->sideDrive->Set(-1);
	}
	if(5>centerdistance&&centerdistance>-5) {
		GoForward();
	} else {
		Center();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {

}
