// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ContainerUp.h"
#include "../Constants.h"

ContainerUp::ContainerUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	initPot = 0;
}

// Called just before this Command runs the first time
void ContainerUp::Initialize() {
	initPot = RobotMap::containerElevatorelevatePot->GetValue();
}

// Called repeatedly when this Command is scheduled to run
void ContainerUp::Execute() {
	RobotMap::containerElevatorclawElevator->Set(0.25);
}

// Make this return true when this Command no longer needs to run execute()
bool ContainerUp::IsFinished() {
	if(RobotMap::containerElevatorelevatePot->GetValue()-initPot>POT_LIFT_DIFFERENCE) {
		return true;
	}
	else {
		return false;
	}
}

// Called once after isFinished returns true
void ContainerUp::End() {
	RobotMap::containerElevatorclawElevator->Set(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ContainerUp::Interrupted() {
	RobotMap::containerElevatorclawElevator->Set(0);
}
