// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LiftUp.h"
#include "../Constants.h"

LiftUp::LiftUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
//	Requires(Robot::toteElevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
//	initPot = 0; //Stores the pot value at the start of the command
}

// Called just before this Command runs the first time
void LiftUp::Initialize() {
//	initPot = RobotMap::toteElevatortotePot->GetValue(); //Store the initial pot value
	Robot::toteElevator->setpoint+=kPOT_LIFT_DIFFERENCE;
}

// Called repeatedly when this Command is scheduled to run
void LiftUp::Execute() {
//	RobotMap::toteElevatortoteDrive->Set(0.25); //Drive the motor forward
//	Robot::toteElevator->PIDLiftControl();
}

// Make this return true when this Command no longer needs to run execute()
bool LiftUp::IsFinished() {
//	if(RobotMap::toteElevatortotePot->GetValue()-initPot<POT_LIFT_DIFFERENCE) { //When the lift travels the length of a tote, stop
//		return false;
//	}
//	else {
		return true; //Otherwise, keep going
//	}
}

// Called once after isFinished returns true
void LiftUp::End() {
//	RobotMap::toteElevatortoteDrive->Set(0); //Stop the motor when the command ends
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LiftUp::Interrupted() {
//	RobotMap::toteElevatortoteDrive->Set(0);
}
