// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LiftMove.h"

LiftMove::LiftMove() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::toteElevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void LiftMove::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void LiftMove::Execute() {
	Robot::toteElevator->PIDLiftControl();
	Robot::toteElevator->limitBottom->Get();
	if(((Robot::toteElevator->limitBottom->Get()) && (Robot::toteElevator->output < 0))  ||  ((Robot::toteElevator->limitTop->Get()) && (Robot::toteElevator->output > 0))) {
		Robot::toteElevator->output=0;
		Robot::toteElevator->setpoint=Robot::toteElevator->totePot->GetValue();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool LiftMove::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void LiftMove::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LiftMove::Interrupted() {

}
